#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    update-alternatives --install /usr/bin/gnome-www-browser \
        gnome-www-browser /usr/bin/cyberfox 40

    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /usr/bin/cyberfox 40
fi


