# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Bookmarks
#define bookmarks_heading Bookmarks

#define bookmarks_toolbarfolder Bookmarks Toolbar Folder
#define bookmarks_toolbarfolder_description Add bookmarks to this folder to see them displayed on the Bookmarks Toolbar

# LOCALIZATION NOTE (getting_started):
# link title for https://8pecxstudios.com/
#define getting_started Getting Started

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading 8pecxstudios

# LOCALIZATION NOTE (firefox_help):
# link title for https://8pecxstudios.com/Forums/viewforum.php?f=8
#define firefox_help Help and Tutorials

# LOCALIZATION NOTE (Cyberfox_customize):
# link title for https://8pecxstudios.com/Forums/viewforum.php?f=11
#define firefox_customize Customize Cyberfox

# LOCALIZATION NOTE (firefox_community):
# link title for https://8pecxstudios.com/Forums/index.php
#define firefox_community Get Involved

# LOCALIZATION NOTE (firefox_about):
# link title for https://8pecxstudios.com/about-us
#define firefox_about About Us

# LOCALIZATION NOTE (firefox_feedback):
# link title for browser feedback page
# currently used by Metro only: https://8pecxstudios.com/Forums/viewforum.php?f=9
#define firefox_feedback User Reviews

#unfilter emptyLines
