.TH CYBERFOX 1 2017-07-01 cyberfox
.SH NAME
cyberfox \- fast, stable and reliable, x64-bit web browser from 8pecxstudios

.SH SYNOPSIS
.B cyberfox
[\fIOPTIONS\fR] [\fIurl\fR]

.SH DESCRIPTION
\fBCyberfox\fR is designed by 8pecxstudios, taking over where Mozilla left off, working to make a fast, stable & reliable 64bit web browser accessible to all. 8pecxstudios have applied many changes to enhance your browsing experience by allowing you more freedom to customize your experience at the same time changes to help protect you’re privacy.

.SH USAGE
\fBcyberfox\fR is a simple shell script that will set up the
environment for the actual executable.

.SH OPTIONS
A summary of the options supported by \fBcyberfox\fR is included below.

.SS "GTK options"
\fB\-\-gdk-debug=\fR\fIFLAGS\fR
Gdk debugging flags to set
.TP
\fB\-\-gdk-no-debug=\fR\fIFLAGS\fR
Gdk debugging flags to unset
.TP
\fB\-\-gtk-debug=\fR\fIFLAGS\fR
Gtk+ debugging flags to set
.TP
\fB\-\-gtk-no-debug=\fR\fIFLAGS\fR
Gtk+ debugging flags to unset
.TP
\fB\-\-gtk-module=\fR\fIMODULE\fR
Load an additional Gtk module

.SS "X11 options"
.TP
.BI \-\-display= DISPLAY
X display to use
.TP
.B \--sync
Make X calls synchronous
.TP
.B \-\-no-xshm
Don't use X shared memory extension
.TP
.BI \-\-xim-preedit= STYLE
.TP
.BI \-\-xim-status= STYLE
.TP
.B \-\-g-fatal-warnings
Make all warnings fatal

.SS "Cyberfox options"
.TP
.B \-h, \-help
Show summary of options.
.TP
\fB\-height\fR \fIvalue\fR
Set height of startup window to \fIvalue\fR.
.TP
\fB\-width\fR \fIvalue\fR
Set width of startup window to \fIvalue\fR.
.TP
.B \-v, \-version
Print \fB/usr/bin/cyberfox-bin\fR version.
.TP
\fB\-CreateProfile\fR \fIprofile\fR
Create \fIprofile\fR.
.TP
\fB\-P\fR \fIprofile\fR
Start with \fIprofile\fR.
.TP
.B \-ProfileManager
Start with profile manager.
.TP
\fB\-UILocale\fR \fIlang-region\fR
Start with \fIlang-region\fR resources.
.TP
\fB\-contentLocale\fR \fIlang-region\fR
Start with \fIlang-region\fR resources.
.TP
\fB\-remote\fR \fIcommand\fR
Execute \fIcommand\fR in an already running Cyberfox process.  For more info,
see: \fIhttp://www.mozilla.org/unix/remote.html\fR
.TP
.B \-no-remote
Don't try to control an already running instance.
.TP
.B \-jsconsole
Start with Javascript Console
.TP
\fB\-chrome\fR \fIurl\fR
Load the specified chrome.
.TP
\fB\-new-window\fR \fIurl\fR
Open URL in a new window if Cyberfox is already running.
.TP
\fB\-new-tab\fR \fIurl\fR
Open URL in a new tab if Cyberfox is already running.
.TP
\fB\-preferences\fR
Open Cyberfox preferences menu.
.TP
.B \-safe-mode
Disables extensions and themes for this session.
.TP

.SH FILES
\fI/usr/bin/cyberfox\fR - shell script wrapping
\fBcyberfox\fR
.br
\fI/usr/lib/cyberfox/cyberfox\fR - \fBcyberfox\fR
executable

.SH VERSION
3.0

.SH BUGS
To report a bug, please visit \fIhttps://8pecxstudios.com/Forums/index.php\fR

.SH AUTHOR
This manual page was written by hawkeye116477, based on Mozilla Firefox's manpage.
