# -*- Mode: HTML -*-
<p>Built from <a href="ftp://ftp.mozilla.org/pub/firefox/releases/34.0/source/firefox-34.0.source.tar.bz2">firefox-34.0.source.tar.bz2</a></p>
<p>B2F64BFE3DF7B4F6AABA755E40413ACF452825A41363FDAA49F730449C9357AADE9A2B525EDFDC347C0ED27FEAD1A0FE7997E91486D14A32D2C1D216E2207388</p>
<p>Get Cyberfox source code <a href="https://8pecxstudios.com/Forums/viewtopic.php?f=8&t=7#p7">Cyberfox.SourceCode.tar.bz2</a></P>
