[CustomMessages]

;Don't translate this.
ApplicationDescription=Cyberfox delivers safe, easy web browsing. A familiar user interface, enhanced security features including protection from online identity theft, and integrated search let you get the most out of the web.

;English
en.ProcessName={#MyAppName}
en.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
en.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
en.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
en.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
en.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
en.CreateStartMenuIcons=Create start menu icons
en.SetBrowserDefaults=Set As Default Web Browser
en.DeleteProfileData=Do you want to delete your profile data?
en.ConfirmDeleteProfileData=Are you sure this can not be undone!
en.CleanInstallDescription=Perform clean installation.
en.CleanInstallGroupDescription=Installation Options
en.PocketInstallDescription=Install firefox pocket (Optional)
en.SystemAddonsGroupDescription=System Addons
en.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
en.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Albanian
al.ProcessName={#MyAppName}
al.IsAppRunning= tashmë është i rrjedhshëm, Ju lutemi mbyllni {#MyAppName} pastaj të drejtuar installer përsëri.
al.IsAppRunningUninstall= tashmë është i rrjedhshëm, Ju lutemi mbyllni {#MyAppName} pastaj të drejtuar Fshirës përsëri.
al.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
al.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
al.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
al.CreateStartMenuIcons=Krijo Start Menu ikona
al.SetBrowserDefaults=Bëje Si Default Web Browser
al.DeleteProfileData=A dëshironi të fshini të dhënat e profilit tuaj?
al.ConfirmDeleteProfileData=A jeni i sigurt se kjo nuk mund të zhbëhet!
al.CleanInstallDescription=Perform clean installation.
al.CleanInstallGroupDescription=Installation Options
al.PocketInstallDescription=Install firefox pocket (Optional)
al.SystemAddonsGroupDescription=System Addons
al.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
al.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Afrikaans
af.ProcessName={#MyAppName}
af.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
af.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
af.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
af.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
af.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
af.CreateStartMenuIcons=Create start menu icons
af.SetBrowserDefaults=Set As Default Web Browser
af.DeleteProfileData=Do you want to delete your profile data?
af.ConfirmDeleteProfileData=Are you sure this can not be undone!
af.CleanInstallDescription=Perform clean installation.
af.CleanInstallGroupDescription=Installation Options
af.PocketInstallDescription=Install firefox pocket (Optional)
af.SystemAddonsGroupDescription=System Addons
af.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
af.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Arabic
ar.ProcessName={#MyAppName}
ar.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
ar.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
ar.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
ar.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
ar.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
ar.CreateStartMenuIcons=Create start menu icons
ar.SetBrowserDefaults=Set As Default Web Browser
ar.DeleteProfileData=Do you want to delete your profile data?
ar.ConfirmDeleteProfileData=Are you sure this can not be undone!
ar.CleanInstallDescription=Perform clean installation.
ar.CleanInstallGroupDescription=Installation Options
ar.PocketInstallDescription=Install firefox pocket (Optional)
ar.SystemAddonsGroupDescription=System Addons
ar.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
ar.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Bengali
be.ProcessName={#MyAppName}
be.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
be.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
be.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
be.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
be.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
be.CreateStartMenuIcons=Create start menu icons
be.SetBrowserDefaults=Set As Default Web Browser
be.DeleteProfileData=Do you want to delete your profile data?
be.ConfirmDeleteProfileData=Are you sure this can not be undone!
be.CleanInstallDescription=Perform clean installation.
be.CleanInstallGroupDescription=Installation Options
be.PocketInstallDescription=Install firefox pocket (Optional)
be.SystemAddonsGroupDescription=System Addons
be.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
be.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Bosnian
bo.ProcessName={#MyAppName}
bo.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
bo.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
bo.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
bo.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
bo.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
bo.CreateStartMenuIcons=Create start menu icons
bo.SetBrowserDefaults=Set As Default Web Browser
bo.DeleteProfileData=Do you want to delete your profile data?
bo.ConfirmDeleteProfileData=Are you sure this can not be undone!
bo.CleanInstallDescription=Perform clean installation.
bo.CleanInstallGroupDescription=Installation Options
bo.PocketInstallDescription=Install firefox pocket (Optional)
bo.SystemAddonsGroupDescription=System Addons
bo.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
bo.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;BrazilianPortuguese
br_pt.ProcessName={#MyAppName}
br_pt.IsAppRunning= já está em execução, feche {#MyAppName} em seguida, execute o instalador novamente.
br_pt.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
br_pt.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
br_pt.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
br_pt.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
br_pt.CreateStartMenuIcons=Criar ícones do menu de início
br_pt.SetBrowserDefaults=Definir como navegador padrão
br_pt.DeleteProfileData=Você quer apagar os dados do perfil?
br_pt.ConfirmDeleteProfileData=Você está certo de que este não pode ser desfeita!
br_pt.CleanInstallDescription=Perform clean installation.
br_pt.CleanInstallGroupDescription=Installation Options
br_pt.PocketInstallDescription=Install firefox pocket (Optional)
br_pt.SystemAddonsGroupDescription=System Addons
br_pt.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
br_pt.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Catalan
ca.ProcessName={#MyAppName}
ca.IsAppRunning= ja s'està executant, tancament{#MyAppName} a continuació, executeu el programa d'instal · lació de nou.
ca.IsAppRunningUninstall= ja s'està executant, tancament{#MyAppName} a continuació, executeu el programa de desinstal de nou.
ca.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
ca.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
ca.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
ca.CreateStartMenuIcons=Crear icones del menú d'inici
ca.SetBrowserDefaults=Establir com a predeterminat del navegador web
ca.DeleteProfileData=Vols eliminar les seves dades del perfil?
ca.ConfirmDeleteProfileData=Està vostè segur que això no es pot desfer!
ca.CleanInstallDescription=Perform clean installation.
ca.CleanInstallGroupDescription=Installation Options
ca.PocketInstallDescription=Install firefox pocket (Optional)
ca.SystemAddonsGroupDescription=System Addons
ca.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
ca.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Chinese (Simplified)
cns.ProcessName={#MyAppName}
cns.IsAppRunning= 已经在运行，请关闭 {#MyAppName} 然后再次运行安装程序。
cns.IsAppRunningUninstall= 已经在运行，请关闭 {#MyAppName} 然后再次运行卸载程序。
cns.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
cns.Isx64BitOS=我们很抱歉！但你无法安装在Windows86操作系统{#MyAppName}64位。
cns.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
cns.CreateStartMenuIcons=创建开始菜单图标
cns.SetBrowserDefaults=设置为默认Web浏览器
cns.DeleteProfileData=你想删除您的个人资料数据？
cns.ConfirmDeleteProfileData=你确定这不能撤消！
cns.CleanInstallDescription=Perform clean installation.
cns.CleanInstallGroupDescription=Installation Options
cns.PocketInstallDescription=Install firefox pocket (Optional)
cns.SystemAddonsGroupDescription=System Addons
cns.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
cns.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Corsican
cr.ProcessName={#MyAppName}
cr.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
cr.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
cr.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
cr.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
cr.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
cr.CreateStartMenuIcons=Create start menu icons
cr.SetBrowserDefaults=Set As Default Web Browser
cr.DeleteProfileData=Do you want to delete your profile data?
cr.ConfirmDeleteProfileData=Are you sure this can not be undone!
cr.CleanInstallDescription=Perform clean installation.
cr.CleanInstallGroupDescription=Installation Options
cr.PocketInstallDescription=Install firefox pocket (Optional)
cr.SystemAddonsGroupDescription=System Addons
cr.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
cr.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Croatian
cro.ProcessName={#MyAppName}
cro.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
cro.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
cro.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
cro.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
cro.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
cro.CreateStartMenuIcons=Create start menu icons
cro.SetBrowserDefaults=Set As Default Web Browser
cro.DeleteProfileData=Do you want to delete your profile data?
cro.ConfirmDeleteProfileData=Are you sure this can not be undone!
cro.CleanInstallDescription=Perform clean installation.
cro.CleanInstallGroupDescription=Installation Options
cro.PocketInstallDescription=Install firefox pocket (Optional)
cro.SystemAddonsGroupDescription=System Addons
cro.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
cro.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Czech
cz.ProcessName={#MyAppName}
cz.IsAppRunning= je již spuštěna, prosím zavřete {#MyAppName} spusťte instalační program znovu.
cz.IsAppRunningUninstall= je již spuštěna, prosím zavřete  {#MyAppName} spusťte odinstalační program znovu.
cz.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
cz.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
cz.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
cz.CreateStartMenuIcons=Vytvořte počáteční ikony v menu
cz.SetBrowserDefaults=Nastavit jako výchozí webový prohlížeč
cz.DeleteProfileData=Chcete-li odstranit data profilu?
cz.ConfirmDeleteProfileData=Jsi si jistý, že to nelze vrátit zpět!
cz.CleanInstallDescription=Perform clean installation.
cz.CleanInstallGroupDescription=Installation Options
cz.PocketInstallDescription=Install firefox pocket (Optional)
cz.SystemAddonsGroupDescription=System Addons
cz.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
cz.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Danish
da.ProcessName={#MyAppName}
da.IsAppRunning= allerede kører, Luk {#MyAppName} derefter køre installationsprogrammet igen.
da.IsAppRunningUninstall= allerede kører, Luk  {#MyAppName} tderefter køre afinstallationsprogrammet igen.
da.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
da.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
da.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
da.CreateStartMenuIcons=Opret Start menusymboler
da.SetBrowserDefaults=Indstil som standard webbrowser
da.DeleteProfileData=Ønsker du at slette din profil data?
da.ConfirmDeleteProfileData=Er du sikker på, det kan ikke fortrydes!
da.CleanInstallDescription=Perform clean installation.
da.CleanInstallGroupDescription=Installation Options
da.PocketInstallDescription=Install firefox pocket (Optional)
da.SystemAddonsGroupDescription=System Addons
da.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
da.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;German
de.ProcessName={#MyAppName}
de.IsAppRunning= läuft noch. Bitte schliessen sie {#MyAppName} und starten sie den Installationsprozess erneut.
de.IsAppRunningUninstall= läuft noch. Bitte schliessen sie {#MyAppName} und führen Sie das Deinstallationsprogramm wieder aus.
de.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
de.Isx64BitOS=Entschuldigung, aber Sie können {#MyAppName} x64 in einem Windows x86 Betriebssystem nicht installieren!
de.CyberCTRInstallDescription=Installiert CyberCTR [Empfohlen] (Optional)
de.CreateStartMenuIcons=Neues Startmenü Icons
de.SetBrowserDefaults=Als Standard Web Browser
de.DeleteProfileData=Möchten Sie Ihre Profildaten löschen?
de.ConfirmDeleteProfileData=Sind Sie sicher? Es kann nicht rückgängig gemacht werden!
de.CleanInstallDescription=Führt eine saubere Installation aus.
de.CleanInstallGroupDescription=Installation Optionen
de.PocketInstallDescription=Installiert Firefox Pocket (Optional)
de.SystemAddonsGroupDescription=Zusätzliche Systemkomponente
de.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
de.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Dutch
nl.ProcessName={#MyAppName}
nl.IsAppRunning= wordt al uitgevoerd, Sluit {#MyAppName} dan weer het installatieprogramma.
nl.IsAppRunningUninstall= wordt al uitgevoerd, Sluit {#MyAppName} opnieuw uit te voeren de uninstaller.
nl.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
nl.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
nl.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
nl.CreateStartMenuIcons=Maak start menu iconen
nl.SetBrowserDefaults=Instellen als standaard webbrowser
nl.DeleteProfileData=Wilt u uw profiel gegevens te verwijderen?
nl.ConfirmDeleteProfileData=Bent u zeker dat dit kan niet ongedaan gemaakt worden!
nl.CleanInstallDescription=Perform clean installation.
nl.CleanInstallGroupDescription=Installation Options
nl.PocketInstallDescription=Install firefox pocket (Optional)
nl.SystemAddonsGroupDescription=System Addons
nl.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
nl.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Finnish
fi.ProcessName={#MyAppName}
fi.IsAppRunning= on jo käynnissä, sulje {#MyAppName} suorita sitten asennusohjelma uudelleen.
fi.IsAppRunningUninstall= on jo käynnissä, sulje {#MyAppName} suorita asennuksen poisto uudelleen.
fi.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
fi.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
fi.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
fi.CreateStartMenuIcons=Luo Käynnistä-valikon kuvakkeet
fi.SetBrowserDefaults=Aseta Web-oletusselaimeksi
fi.DeleteProfileData=Haluatko poistaa profiilisi tietoja?
fi.ConfirmDeleteProfileData=Oletko varma, että tämä ei voi perua!
fi.CleanInstallDescription=Perform clean installation.
fi.CleanInstallGroupDescription=Installation Options
fi.PocketInstallDescription=Install firefox pocket (Optional)
fi.SystemAddonsGroupDescription=System Addons
fi.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
fi.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;French
fr.ProcessName={#MyAppName}
fr.IsAppRunning= est en cours d’exécution. Veuillez fermer {#MyAppName} puis redémarrer de nouveau le programme d’installation.
fr.IsAppRunningUninstall= est en cours d’exécution. Veuillez fermer {#MyAppName} puis exécutez à nouveau le programme de désinstallation.
fr.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
fr.Isx64BitOS=Désolé ! Il est impossible d’installer la version 64 bits de {#MyAppName} sur un système Windows de 32 bits (x86).
fr.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
fr.CreateStartMenuIcons=Créer les icônes du menu de démarrage
fr.SetBrowserDefaults=Définir comme navigateur par défaut
fr.DeleteProfileData=Voulez-vous effacer les données personnelles de votre profil ?
fr.ConfirmDeleteProfileData=Êtes-vous certain ? Cette opération ne peut être annulée !
fr.CleanInstallDescription=Perform clean installation.
fr.CleanInstallGroupDescription=Installation Options
fr.PocketInstallDescription=Install firefox pocket (Optional)
fr.SystemAddonsGroupDescription=System Addons
fr.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
fr.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Greek
gr.ProcessName={#MyAppName}
gr.IsAppRunning= εκτελείται ήδη, παρακαλώ κλείστε {#MyAppName} Στη συνέχεια, εκτελέστε ξανά το πρόγραμμα εγκατάστασης.
gr.IsAppRunningUninstall= εκτελείται ήδη, παρακαλώ κλείστε {#MyAppName} Στη συνέχεια, εκτελέστε ξανά το πρόγραμμα απεγκατάστασης.
gr.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
gr.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
gr.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
gr.CreateStartMenuIcons=Δημιουργήστε εικονίδια του μενού έναρξης
gr.SetBrowserDefaults=Ορισμός ως προεπιλεγμένου προγράμματος περιήγησης Web
gr.DeleteProfileData=Μήπως θέλετε να διαγράψετε τα δεδομένα του προφίλ σας;
gr.ConfirmDeleteProfileData=Είσαι σίγουρος ότι αυτό δεν μπορεί να αναιρεθεί!
gr.CleanInstallDescription=Perform clean installation.
gr.CleanInstallGroupDescription=Installation Options
gr.PocketInstallDescription=Install firefox pocket (Optional)
gr.SystemAddonsGroupDescription=System Addons
gr.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
gr.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Hebrew
he.ProcessName={#MyAppName}
he.IsAppRunning= כבר פועל, אנא סגור {#MyAppName} לאחר מכן הפעל שוב את תוכנית ההתקנה.
he.IsAppRunningUninstall= כבר פועל, אנא סגור {#MyAppName} לאחר מכן להפעיל את מסיר שוב.
he.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
he.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
he.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
he.CreateStartMenuIcons=ליצור סמלי תפריט התחל
he.SetBrowserDefaults=הגדר כדפדפן ברירת מחדל
he.DeleteProfileData=האם ברצונך למחוק את נתוני הפרופיל שלך?
he.ConfirmDeleteProfileData=האם אתה בטוח שזה לא ניתן לבטל!
he.CleanInstallDescription=Perform clean installation.
he.CleanInstallGroupDescription=Installation Options
he.PocketInstallDescription=Install firefox pocket (Optional)
he.SystemAddonsGroupDescription=System Addons
he.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
he.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Hindi
hi.ProcessName={#MyAppName}
hi.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
hi.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
hi.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
hi.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
hi.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
hi.CreateStartMenuIcons=Create start menu icons
hi.SetBrowserDefaults=Set As Default Web Browser
hi.DeleteProfileData=Do you want to delete your profile data?
hi.ConfirmDeleteProfileData=Are you sure this can not be undone!
hi.CleanInstallDescription=Perform clean installation.
hi.CleanInstallGroupDescription=Installation Options
hi.PocketInstallDescription=Install firefox pocket (Optional)
hi.SystemAddonsGroupDescription=System Addons
hi.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
hi.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Hungarian
hu.ProcessName={#MyAppName}
hu.IsAppRunning= már fut, zárja {#MyAppName} majd futtassa újra a telepítőt.
hu.IsAppRunningUninstall= már fut, zárja {#MyAppName} majd futtassa az eltávolító újra.
hu.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
hu.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
hu.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
hu.CreateStartMenuIcons=Hozzon létre a Start menü ikonok
hu.SetBrowserDefaults=Beállítás alapértelmezett böngésző
hu.DeleteProfileData=Szeretné törölni a profil adatait?
hu.ConfirmDeleteProfileData=Biztos benne, hogy ez nem lehet visszavonni!
hu.CleanInstallDescription=Perform clean installation.
hu.CleanInstallGroupDescription=Installation Options
hu.PocketInstallDescription=Install firefox pocket (Optional)
hu.SystemAddonsGroupDescription=System Addons
hu.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
hu.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Indonesian
in.ProcessName={#MyAppName}
in.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
in.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
in.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
in.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
in.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
in.CreateStartMenuIcons=Create start menu icons
in.SetBrowserDefaults=Set As Default Web Browser
in.DeleteProfileData=Do you want to delete your profile data?
in.ConfirmDeleteProfileData=Are you sure this can not be undone!
in.CleanInstallDescription=Perform clean installation.
in.CleanInstallGroupDescription=Installation Options
in.PocketInstallDescription=Install firefox pocket (Optional)
in.SystemAddonsGroupDescription=System Addons
in.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
in.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Italian
it.ProcessName={#MyAppName}
it.IsAppRunning= è già in esecuzione, chiudere {#MyAppName} quindi eseguire nuovamente il programma di installazione.
it.IsAppRunningUninstall= è già in esecuzione, chiudere {#MyAppName} quindi eseguire nuovamente il programma di disinstallazione.
it.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
it.Isx64BitOS=Chiediamo scusa, ma non potete installare {#MyAppName} x64 su un sistema con Windows x86!
it.CyberCTRInstallDescription=Installa CyberCTR [Consigliato] (Optional)
it.CreateStartMenuIcons=Creare icone del menu Start
it.SetBrowserDefaults=Imposta come Web-Browser predefinito.
it.DeleteProfileData=Vuoi eliminare i dati del tuo profilo?
it.ConfirmDeleteProfileData=Sei sicuro? Ciò non può essere ripristinato!
it.CleanInstallDescription=Esegui un'installazione pulita.
it.CleanInstallGroupDescription=Opzioni per l'installazione
it.PocketInstallDescription=Installa Firefox Pocket (Optional)
it.SystemAddonsGroupDescription=Componenti aggiuntivi di sistema
it.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
it.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Korean
kor.ProcessName={#MyAppName}
kor.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
kor.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
kor.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
kor.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
kor.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
kor.CreateStartMenuIcons=Create start menu icons
kor.SetBrowserDefaults=Set As Default Web Browser
kor.DeleteProfileData=Do you want to delete your profile data?
kor.ConfirmDeleteProfileData=Are you sure this can not be undone!
kor.CleanInstallDescription=Perform clean installation.
kor.CleanInstallGroupDescription=Installation Options
kor.PocketInstallDescription=Install firefox pocket (Optional)
kor.SystemAddonsGroupDescription=System Addons
kor.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
kor.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Japanese
ja.ProcessName={#MyAppName}
ja.IsAppRunning= はすでに実行されています。{#MyAppName} を閉じて、もう一度インストーラーを実行してください。
ja.IsAppRunningUninstall= はすでに実行されています。{#MyAppName} を閉じて、もう一度アンインストーラーを実行してください。
ja.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
ja.Isx64BitOS= 申し訳ございませんが、32 ビットの Windows には 64 ビットの {#MyAppName} をインストールできません。
ja.CyberCTRInstallDescription=CyberCTR をインストールする[推奨] (オプション)
ja.CreateStartMenuIcons=スタート メニューにアイコンを作成
ja.SetBrowserDefaults=既定の Web ブラウザに設定する
ja.DeleteProfileData=プロファイル データを削除しますか？
ja.ConfirmDeleteProfileData=元に戻すことはできませんがよろしいですか？
ja.CleanInstallDescription=クリーン インストールを実行する
ja.CleanInstallGroupDescription=インストール オプション
ja.PocketInstallDescription=Firefox Pocket をインストールする(オプション)
ja.SystemAddonsGroupDescription=システム アドオン
ja.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
ja.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Norwegian
nr.ProcessName={#MyAppName}
nr.IsAppRunning= er allerede i gang, Vennligst lukk {#MyAppName} deretter kjøre installasjonsprogrammet på nytt.
nr.IsAppRunningUninstall= er allerede i gang, Vennligst lukk {#MyAppName} deretter kjøre avinstalleringsprogrammet igjen.
nr.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
nr.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
nr.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
nr.CreateStartMenuIcons=Lag start menyikoner
nr.SetBrowserDefaults=Angi som standard Web Browser
nr.DeleteProfileData=Ønsker du å slette din profil data?
nr.ConfirmDeleteProfileData=Er du sikker på at dette kan ikke angres!
nr.CleanInstallDescription=Perform clean installation.
nr.CleanInstallGroupDescription=Installation Options
nr.PocketInstallDescription=Install firefox pocket (Optional)
nr.SystemAddonsGroupDescription=System Addons
nr.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
nr.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Polish
pl.ProcessName={#MyAppName}
pl.IsAppRunning= jest już uruchomiony. Proszę zamknąć {#MyAppName}, a następnie ponownie uruchomić instalator.
pl.IsAppRunningUninstall= jest już uruchomiony. Proszę zamknąć {#MyAppName}, a następnie ponownie uruchomić deinstalator.
pl.IsAppRunningOnVista=Uwaga: Windows Vista nie jest już dłużej wspierany, ale wciąż można uruchomić {#MyAppName} na tej platformie. Naciśnij OK, by kontynuować!
pl.Isx64BitOS=Przykro nam, ale nie możesz zainstalować 64-bitowego programu {#MyAppName} na systemie 32-bitowym.
pl.CyberCTRInstallDescription=Zainstaluj CyberCTR [Zalecane] (Opcjalne)
pl.CreateStartMenuIcons=Dodaj ikony do menu start
pl.SetBrowserDefaults=Ustaw jako domyślną przeglądarkę internetową
pl.DeleteProfileData=Czy chcesz usunąć swoje dane z profilu?
pl.ConfirmDeleteProfileData=Czy jesteś pewny/a? Tego nie można cofnąć!
pl.CleanInstallDescription=Wykonaj czystą instalację.
pl.CleanInstallGroupDescription=Opcje instalacji
pl.PocketInstallDescription=Zainstaluj Firefox Pocket (Opcjalne)
pl.SystemAddonsGroupDescription=Dodatki systemowe
pl.UpdateShortcut=Sprawdź aktualizacje
;Localization note must preserve %n this is a new line break.
pl.SystemCpuUnsupported=Ten komputer ma starszy procesor, który nie obsługuje zestawu instrukcji SSE2. %n%nCyberfox 49.0 i późniejsze wersje nie uruchomią się na tym komputerze.
;Portuguese
pt.ProcessName={#MyAppName}
pt.IsAppRunning= já está em execução, feche {#MyAppName} em seguida, execute o instalador novamente.
pt.IsAppRunningUninstall= já está em execução, feche {#MyAppName} em seguida, executar o desinstalador novamente.
pt.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
pt.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
pt.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
pt.CreateStartMenuIcons=Create start menu icons
pt.SetBrowserDefaults=Definir como navegador padrão
pt.DeleteProfileData=Você quer apagar os dados do perfil?
pt.ConfirmDeleteProfileData=Você está certo de que este não pode ser desfeita!
pt.CleanInstallDescription=Perform clean installation.
pt.CleanInstallGroupDescription=Installation Options
pt.PocketInstallDescription=Install firefox pocket (Optional)
pt.SystemAddonsGroupDescription=System Addons
pt.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
pt.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Russian
ru.ProcessName={#MyAppName}
ru.IsAppRunning= уже запущен, закройте {#MyAppName} и запустите программу установки повторно.
ru.IsAppRunningUninstall= уже запущен, закройте {#MyAppName} и запустите программу удаления повторно.
ru.IsAppRunningOnVista=Внимание: Windows Vista больше не поддерживается, но мы можете запустить программу в этой системе - нажмите ОК для продолжения!
ru.Isx64BitOS=Простите, но Вы не можете установить 64-битную версию {#MyAppName} в 32-битной ОС.
ru.CyberCTRInstallDescription=Установить CyberCTR [рекомендуется] (необязательно)
ru.CreateStartMenuIcons=Создать ярлыки в меню «Пуск»
ru.SetBrowserDefaults=Установить браузером по умолчанию
ru.DeleteProfileData=Вы ходите удалить Ваши личные данные?
ru.ConfirmDeleteProfileData=Вы уверены? Эта операция не может быть отменена!
ru.CleanInstallDescription=Выполнить чистую установку.
ru.CleanInstallGroupDescription=Настройки установки
ru.PocketInstallDescription=Установить Firefox pocket (необязательно)
ru.SystemAddonsGroupDescription=Системные дополнения
ru.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
ru.SystemCpuUnsupported=На Вашем компьютере установлен старый процессор, не поддерживающий набор инструкций SSE2. %n%nCyberfox 49.0 и более поздних версий не может быть запущен на этом компьютере.
;SerbianCyrillic
sbc.ProcessName={#MyAppName}
sbc.IsAppRunning= је већ покренут, затворите Молимо {#MyAppName} затим покрените инсталер поново.
sbc.IsAppRunningUninstall= је већ покренут, затворите Молимо {#MyAppName} затим покрените Унинсталлер поново.
sbc.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
sbc.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
sbc.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
sbc.CreateStartMenuIcons=Create start menu icons
sbc.SetBrowserDefaults=Сет Ас Дефаулт Веб Бровсер
sbc.DeleteProfileData=Да ли желите да избришете податке на профилу?
sbc.ConfirmDeleteProfileData=Да ли сте сигурни да не може да се опозове!
sbc.CleanInstallDescription=Perform clean installation.
sbc.CleanInstallGroupDescription=Installation Options
sbc.PocketInstallDescription=Install firefox pocket (Optional)
sbc.SystemAddonsGroupDescription=System Addons
sbc.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
sbc.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;SerbianLatin
sbl.ProcessName={#MyAppName}
sbl.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
sbl.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
sbl.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
sbl.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
sbl.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
sbl.CreateStartMenuIcons=Create start menu icons
sbl.SetBrowserDefaults=Set As Default Web Browser
sbl.DeleteProfileData=Do you want to delete your profile data?
sbl.ConfirmDeleteProfileData=Are you sure this can not be undone!
sbl.CleanInstallDescription=Perform clean installation.
sbl.CleanInstallGroupDescription=Installation Options
sbl.PocketInstallDescription=Install firefox pocket (Optional)
sbl.SystemAddonsGroupDescription=System Addons
sbl.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
sbl.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Slovenian
sl.ProcessName={#MyAppName}
sl.IsAppRunning= že teče, Prosimo, zaprite {#MyAppName} nato ponovno zaženite namestitveni program.
sl.IsAppRunningUninstall= že teče, Prosimo, zaprite {#MyAppName} nato ponovno zaženite uninstaller.
sl.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
sl.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
sl.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
sl.CreateStartMenuIcons=Create start menu icons
sl.SetBrowserDefaults=Nastavi kot privzeti spletni brskalnik
sl.DeleteProfileData=Ali želite izbrisati podatke profila?
sl.ConfirmDeleteProfileData=Ali ste prepričani, da to ni mogoče razveljaviti!
sl.CleanInstallDescription=Perform clean installation.
sl.CleanInstallGroupDescription=Installation Options
sl.PocketInstallDescription=Install firefox pocket (Optional)
sl.SystemAddonsGroupDescription=System Addons
sl.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
sl.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Swedish
sw.ProcessName={#MyAppName}
sw.IsAppRunning= is already running, Please close {#MyAppName} then run the installer again.
sw.IsAppRunningUninstall= is already running, Please close {#MyAppName} then run the uninstaller again.
sw.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
sw.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
sw.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
sw.CreateStartMenuIcons=Create start menu icons
sw.SetBrowserDefaults=Set As Default Web Browser
sw.DeleteProfileData=Do you want to delete your profile data?
sw.ConfirmDeleteProfileData=Are you sure this can not be undone!
sw.CleanInstallDescription=Perform clean installation.
sw.CleanInstallGroupDescription=Installation Options
sw.PocketInstallDescription=Install firefox pocket (Optional)
sw.SystemAddonsGroupDescription=System Addons
sw.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
sw.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Turkish
tr.ProcessName={#MyAppName}
tr.IsAppRunning= zaten çalışıyor, Lütfen {#MyAppName} kapatın ve kurulumu tekrar çalıştırın.
tr.IsAppRunningUninstall= zaten çalışıyor, Lütfen {#MyAppName} sonra tekrar kaldırıcı çalıştırın.
tr.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
tr.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
tr.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
tr.CreateStartMenuIcons=Başlat menüsü ikonları oluştur
tr.SetBrowserDefaults=Varsayılan tarayıcı olarak ayarla
tr.DeleteProfileData=Profil verilerinizi de silmek istiyor musunuz?
tr.ConfirmDeleteProfileData=Emin misiniz bu işlem geri alınamaz!
tr.CleanInstallDescription=Temiz Bir Kurulum Gerçekleştir.
tr.CleanInstallGroupDescription=Kurulum Seçenekleri
tr.PocketInstallDescription=Install firefox pocket (Optional)
tr.SystemAddonsGroupDescription=System Addons
tr.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
tr.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Spanish
en_es.ProcessName={#MyAppName}
en_es.IsAppRunning= ya se está ejecutando, cierre {#MyAppName} a continuación, ejecute el programa de instalación de nuevo.
en_es.IsAppRunningUninstall= ya se está ejecutando, cierre {#MyAppName} a continuación, ejecute el programa de desinstalación de nuevo.
en_es.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
en_es.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
en_es.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
en_es.CreateStartMenuIcons=Create start menu icons
en_es.SetBrowserDefaults=Establecer como predeterminado del navegador web
en_es.DeleteProfileData=¿Quieres eliminar sus datos del perfil?
en_es.ConfirmDeleteProfileData=¿Está usted seguro de que esto no se puede deshacer!
en_es.CleanInstallDescription=Perform clean installation.
en_es.CleanInstallGroupDescription=Installation Options
en_es.PocketInstallDescription=Install firefox pocket (Optional)
en_es.SystemAddonsGroupDescription=System Addons
en_es.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
en_es.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
;Ukrainian
ukr.ProcessName={#MyAppName}
ukr.IsAppRunning= вже запущений, закрийте {#MyAppName} потім запустити програму установки ще раз.
ukr.IsAppRunningUninstall= вже запущений, закрийте {#MyAppName} потім запустити програму видалення знову.
ukr.IsAppRunningOnVista=Warning: Windows Vista is no longer supported, But can still run on this platform, Press OK to continue!
ukr.Isx64BitOS=We are sorry!, But you can not install {#MyAppName} x64 bit on windows x86 OS.
ukr.CyberCTRInstallDescription=Install CyberCTR [Recommended] (Optional)
ukr.CreateStartMenuIcons=Create start menu icons
ukr.SetBrowserDefaults=Встановити за замовчуванням веб-браузера
ukr.DeleteProfileData=Ви хочете видалити дані профілю?
ukr.ConfirmDeleteProfileData=Are you sure this can not be undone!
ukr.CleanInstallDescription=Perform clean installation.
ukr.CleanInstallGroupDescription=Installation Options
ukr.PocketInstallDescription=Install firefox pocket (Optional)
ukr.SystemAddonsGroupDescription=System Addons
ukr.UpdateShortcut=Check for updates
;Localization note must preserve %n this is a new line break.
ukr.SystemCpuUnsupported=This computer has an older CPU that lacks SSE2 instruction set support. %n%nCyberfox 49.0 and later can not run on this computer.
