#include "app.config"
#include "setup.inc"
#include "languages.inc"
#include "messages.inc"
#if Arch == "i368"
#include "customMessages.86.inc"
#elif Arch == "amd64"
#include "customMessages.64.inc"
#endif
#include "tasks.inc"
#include "files.inc"
#include "icons.inc"
#include "registry.registry"
#include "code.inc"
#include "run.inc"