[Tasks]
Name: "cleaninstall"; Description: "{cm:CleanInstallDescription}"; GroupDescription: "{cm:CleanInstallGroupDescription}"; Flags: dontinheritcheck unchecked
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1
Name: "cyberctr"; Description: "{cm:CyberCTRInstallDescription}"; GroupDescription: "{cm:CyberCTRInstallGroupDescription}"
Name: "loop"; Description: "{cm:LoopInstallDescription}"; GroupDescription: "{cm:LoopInstallGroupDescription}"; Flags: unchecked