[Tasks]
Name: "CleanInstall"; Description: "{cm:CleanInstallDescription}"; GroupDescription: "{cm:CleanInstallGroupDescription}"; Flags: dontinheritcheck unchecked
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1
Name: "DefaultAustralis"; Description: "{cm:AustralisDescription}"; GroupDescription: "{cm:AustralisGroupDescription}"