#!/bin/sh

set -e

UPDATENOTIFIERDIR=/var/lib/update-notifier/user.d
MOZ_LIBDIR=/usr/lib/Cyberfox
MOZ_APP_NAME=cyberfox
MOZ_PKG_NAME=cyberfox

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    update-alternatives --install /usr/bin/gnome-www-browser \
        gnome-www-browser /usr/bin/$MOZ_APP_NAME 40

    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /usr/bin/$MOZ_APP_NAME 40
fi
